export type EquityStage = "pair" | "draw" | "board" | "range";

export type Bucket = { id: string; label: string; lo: number; hi: number };

/** Order-of-magnitude shelves. The taught number should sit inside, not on a border. */
export const BROAD: Bucket[] = [
  { id: "u30", label: "до 30%", lo: 0, hi: 33 },
  { id: "b40", label: "35–45%", lo: 33, hi: 46 },
  { id: "b50", label: "45–60%", lo: 46, hi: 63 },
  { id: "b70", label: "65–75%", lo: 63, hi: 80 },
  { id: "b80", label: "80%+", lo: 80, hi: 101 },
];

/** Tighter shelves for a 15bb shove: the call costs about 47%. */
export const RANGE_BUCKETS: Bucket[] = [
  { id: "u40", label: "до 40%", lo: 0, hi: 40 },
  { id: "b44", label: "40–48%", lo: 40, hi: 48 },
  { id: "b52", label: "48–58%", lo: 48, hi: 58 },
  { id: "b62", label: "58–68%", lo: 58, hi: 68 },
  { id: "b72", label: "68–78%", lo: 68, hi: 78 },
  { id: "b85", label: "80%+", lo: 78, hi: 101 },
];

export type EquitySpot = {
  id: string;
  stage: EquityStage;
  street: "Префлоп" | "Флоп" | "Тёрн";
  story: string;
  hero: [string, string];
  /** Null when the opponent is a range, not one hand. */
  villain: [string, string] | null;
  villainLine: string;
  board: string[];
  /** Percent we grade against. */
  equity: number;
  rule: string;
  why: string;
};

export const STAGES: { id: EquityStage; short: string; title: string; lead: string; points: string[] }[] = [
  {
    id: "pair",
    short: "1 · Рука",
    title: "Рука против руки",
    lead: "Обе руки открыты, борда нет. Не считайте ауты — назовите тип.",
    points: [
      "Старшая пара против младшей — около 80%.",
      "Оверкарта — карта старше той, с которой её сравнивают. AK против 22: и туз, и король старше двойки. Это две оверкарты, пара чуть впереди: 50–55%.",
      "Старший туз против младшего с той же картой — 70–75%.",
      "Одномасть добавляет около 3 пунктов, не новую категорию.",
    ],
  },
  {
    id: "draw",
    short: "2 · Дро",
    title: "Ауты против готовой руки",
    lead: "Вы позади. Оверкарта — карта в вашей руке старше всех карт на борде. Чистые ауты: с флопа ×4, с тёрна ×2.",
    points: [
      "AK на флопе Q-7-2: туз и король старше дамы, семёрки и двойки. Это две оверкарты, 6 аутов, около 24%. Гатшот — 4 аута, около 16%.",
      "Стрейт с двух сторон, 8 аутов — около 32%. Голый флеш, 9 — около 36%.",
      "Оверкарта сверху флеша — это уже ближе к 45%, не к 36%.",
      "Грязный аут, который не бьёт готовую руку, не считайте.",
    ],
  },
  {
    id: "board",
    short: "3 · Флоп",
    title: "Кто впереди на борде",
    lead: "Сначала кто впереди сейчас. Потом ауты того, кто позади. Ваша эквити — остаток.",
    points: [
      "Младшая пара не попала во флоп — около 8%, не 18% как на префлопе.",
      "Топ-пара против двух оверкарт — у вас около 75%.",
      "Сет против стрит-дро — около 70%. Дро забирает треть, не «почти ноль».",
      "Комбо-дро против топ-пары — вы уже не андердог, около 55–60%.",
    ],
  },
  {
    id: "range",
    short: "4 · Диапазон",
    title: "Против пуша баттона",
    lead: "Руки нет. Есть широкий пуш 15bb: пары, тузы, бродвей, часть одномастных. Колл просит около 47%.",
    points: [
      "AA и KK — 80%+. QQ — около 72. JJ — около 64. AK — 60–65.",
      "AQ — около 55. AJ и 22 — около 50. Это колл.",
      "ATo — около 42. KQo — около 45. Ниже 47, фолд.",
      "76s — около 36. Красивое дро без цены — фолд.",
    ],
  },
];

export const EQUITY_SPOTS: EquitySpot[] = [
  {
    id: "aa-kk",
    stage: "pair",
    street: "Префлоп",
    story: "Олл-ин до борда. Третий игрок уже сбросил.",
    hero: ["As", "Ad"],
    villain: ["Kh", "Ks"],
    villainLine: "Противник показывает KK",
    board: [],
    equity: 82,
    rule: "Пара против пары: старшая около 80%.",
    why: "У королей три короля, чтобы догнать. Этого мало: тузы выигрывают около 82%.",
  },
  {
    id: "aa-22",
    stage: "pair",
    street: "Префлоп",
    story: "Олл-ин до борда. Третий игрок уже сбросил.",
    hero: ["As", "Ad"],
    villain: ["2c", "2d"],
    villainLine: "Противник показывает 22",
    board: [],
    equity: 82,
    rule: "Старшая пара против младшей — те же 80%, не 95%.",
    why: "Двойки должны попасть в сет или в фулл. Это около 18% у них и 82% у вас.",
  },
  {
    id: "aa-ako",
    stage: "pair",
    street: "Префлоп",
    story: "Олл-ин до борда. Третий игрок уже сбросил.",
    hero: ["As", "Ad"],
    villain: ["Ah", "Kd"],
    villainLine: "Противник показывает AKo",
    board: [],
    equity: 93,
    rule: "Туз против тузов доминирован сильнее, чем пара против пары.",
    why: "Король почти не помогает: общий туз ваш. Около 93%, не 80%.",
  },
  {
    id: "aa-aks",
    stage: "pair",
    street: "Префлоп",
    story: "Олл-ин до борда. Третий игрок уже сбросил.",
    hero: ["As", "Ad"],
    villain: ["Ah", "Kh"],
    villainLine: "Противник показывает AKs",
    board: [],
    equity: 88,
    rule: "Одномастный AK забирает флеши. Это меньше, чем против разномастного.",
    why: "Против AKo было около 93%. Против AKs около 88%: флеш — лишние ауты.",
  },
  {
    id: "jj-ako",
    stage: "pair",
    street: "Префлоп",
    story: "Олл-ин до борда. Третий игрок уже сбросил.",
    hero: ["Jh", "Jd"],
    villain: ["As", "Kd"],
    villainLine: "Противник показывает AKo",
    board: [],
    equity: 57,
    rule: "Пара против двух оверкарт — небольшой фаворит, не фаворит 70%.",
    why: "Валеты впереди AK примерно 57 на 43. Это флип с небольшим перевесом пары.",
  },
  {
    id: "22-ako",
    stage: "pair",
    street: "Префлоп",
    story: "Олл-ин до борда. Третий игрок уже сбросил.",
    hero: ["2c", "2d"],
    villain: ["As", "Kd"],
    villainLine: "Противник показывает AKo",
    board: [],
    equity: 52,
    rule: "Любая пара против двух оверкарт — около 52–55%.",
    why: "Даже двойки чуть впереди AK. Не андердог и не 70%.",
  },
  {
    id: "qq-aks",
    stage: "pair",
    street: "Префлоп",
    story: "Олл-ин до борда. Третий игрок уже сбросил.",
    hero: ["Qs", "Qc"],
    villain: ["Ah", "Kh"],
    villainLine: "Противник показывает AKs",
    board: [],
    equity: 52,
    rule: "Против одномастных оверкарт пара почти монетка.",
    why: "Флеш-ауты AK съедают перевес дам. Около 52%, не 60.",
  },
  {
    id: "ako-aqo",
    stage: "pair",
    street: "Префлоп",
    story: "Олл-ин до борда. Третий игрок уже сбросил.",
    hero: ["As", "Kd"],
    villain: ["Ah", "Qc"],
    villainLine: "Противник показывает AQo",
    board: [],
    equity: 74,
    rule: "Старший кикер того же туза — около 70–75%.",
    why: "Дама доминирована. У AQ остаётся около 26%, в основном свои дамы и редкий стрит.",
  },
  {
    id: "ako-76s",
    stage: "pair",
    street: "Префлоп",
    story: "Олл-ин до борда. Третий игрок уже сбросил.",
    hero: ["As", "Kd"],
    villain: ["7h", "6h"],
    villainLine: "Противник показывает 76s",
    board: [],
    equity: 58,
    rule: "Против одномастного коннектора AK — около 60, не 80.",
    why: "У 76s стрит и флеш. Вам около 58%. Это преимущество, но не доминирование.",
  },
  {
    id: "aks-ako",
    stage: "pair",
    street: "Префлоп",
    story: "Олл-ин до борда. Третий игрок уже сбросил.",
    hero: ["As", "Ks"],
    villain: ["Ah", "Kd"],
    villainLine: "Противник показывает AKo",
    board: [],
    equity: 53,
    rule: "Одномасть против той же разномастной — около +3 пунктов.",
    why: "Не 70% и не «другая рука». Всего около 53%.",
  },

  {
    id: "gut",
    stage: "draw",
    street: "Флоп",
    story: "Вы позади топ-пары. Третий игрок сбросил.",
    hero: ["8s", "7c"],
    villain: ["Kh", "Qd"],
    villainLine: "Противник: топ-пара, KQ",
    board: ["6d", "4h", "Kc"],
    equity: 20,
    rule: "Гатшот: 4 аута × 4 ≈ 16%.",
    why: "Нужна пятёрка. Точный прогон борда даёт 20%: иногда помогает пара, но это всё ещё «до 30».",
  },
  {
    id: "overs",
    stage: "draw",
    street: "Флоп",
    story: "У противника топ-пара. Третий игрок сбросил.",
    hero: ["As", "Kd"],
    villain: ["Qh", "Jc"],
    villainLine: "Противник: топ-пара, QJ",
    board: ["Qd", "8h", "3s"],
    equity: 23,
    rule: "Две оверкарты: 6 аутов × 4 ≈ 24%.",
    why: "Оверкарта — карта старше всего борда. Туз и король старше Q-8-3. В колоде 3 туза и 3 короля. Если они чистые, около 23–24%. Не 35 и не монетка.",
  },
  {
    id: "oesd",
    stage: "draw",
    street: "Флоп",
    story: "У противника топ-пара. Третий игрок сбросил.",
    hero: ["8s", "7c"],
    villain: ["Kh", "Qd"],
    villainLine: "Противник: топ-пара, KQ",
    board: ["6d", "5h", "Kc"],
    equity: 34,
    rule: "OESD: 8 аутов × 4 ≈ 32%.",
    why: "Четвёрка или девятка. Пара 8 или 7 короля не бьёт, ауты почти чистые. Точно 34%.",
  },
  {
    id: "fd",
    stage: "draw",
    street: "Флоп",
    story: "У противника топ-пара без вашего флеша. Третий игрок сбросил.",
    hero: ["9h", "8h"],
    villain: ["Ad", "Kc"],
    villainLine: "Противник: топ-пара, AK",
    board: ["Kh", "7h", "2c"],
    equity: 40,
    rule: "Голый флеш: 9 аутов × 4 ≈ 36%.",
    why: "Девять червей. Точный расчёт 40%: немного добавляют свои пары. Полка та же, 35–45.",
  },
  {
    id: "fd-over",
    stage: "draw",
    street: "Флоп",
    story: "Флеш-дро, и туз старше пары противника. Третий игрок сбросил.",
    hero: ["Ah", "5h"],
    villain: ["Ks", "Qd"],
    villainLine: "Противник: топ-пара, KQ",
    board: ["Kh", "7h", "2d"],
    equity: 46,
    rule: "Флеш плюс оверкарта — уже не 36%.",
    why: "Девять червей и тузы, которые бьют короля. Точно 46%. Это полка 45–60.",
  },
  {
    id: "oesd-turn",
    stage: "draw",
    street: "Тёрн",
    story: "Тёрн пустой, дро не закрылось. Третий игрок сбросил.",
    hero: ["8s", "7c"],
    villain: ["Kh", "Qd"],
    villainLine: "Противник: топ-пара, KQ",
    board: ["6d", "5h", "Kc", "2s"],
    equity: 18,
    rule: "С тёрна ауты × 2. Восемь аутов — около 16%.",
    why: "Одна карта впереди. 8 × 2 = 16, точный прогон 18%.",
  },
  {
    id: "fd-turn",
    stage: "draw",
    street: "Тёрн",
    story: "На тёрне флеш не закрылся, туз всё ещё оверкарта. Третий игрок сбросил.",
    hero: ["Ah", "5h"],
    villain: ["Kd", "Qs"],
    villainLine: "Противник: топ-пара, KQ",
    board: ["Kh", "8h", "2c", "9d"],
    equity: 27,
    rule: "С тёрна голый флеш был бы 9 × 2 ≈ 18. Оверкарта добавляет.",
    why: "Черви плюс тузы. Точно 27% — всё ещё полка «до 30», но не 18.",
  },

  {
    id: "aa-77-flop",
    stage: "board",
    street: "Флоп",
    story: "Флоп мимо обеих пар. Третий игрок сбросил.",
    hero: ["As", "Ad"],
    villain: ["7h", "7c"],
    villainLine: "Противник: 77",
    board: ["Ks", "8d", "2c"],
    equity: 92,
    rule: "Не попавшая младшая пара — 2 аута × 4 ≈ 8%. Вам остальное.",
    why: "На префлопе у семерок было около 18%. Флоп пустой, осталось около 8%. У вас 92%.",
  },
  {
    id: "77-aa-flop",
    stage: "board",
    street: "Флоп",
    story: "Вы младшая пара, флоп мимо. Третий игрок сбросил.",
    hero: ["7h", "7c"],
    villain: ["As", "Ad"],
    villainLine: "Противник: AA",
    board: ["Ks", "8d", "2c"],
    equity: 8,
    rule: "Два аута на сет. 2 × 4 ≈ 8%.",
    why: "Это не префлопные 18%. Доска уже вышла, и она пустая.",
  },
  {
    id: "aq-a9",
    stage: "board",
    street: "Флоп",
    story: "Оба попали в туза, ваш кикер старше. Третий игрок сбросил.",
    hero: ["As", "Qd"],
    villain: ["Ah", "9c"],
    villainLine: "Противник: A9",
    board: ["Ad", "8s", "3c"],
    equity: 86,
    rule: "Доминированный кикер — около 15% у него, не монетка.",
    why: "Ему в основном нужны девятки. Точно у вас 86%.",
  },
  {
    id: "aa-kq",
    stage: "board",
    street: "Флоп",
    story: "У вас оверпара, у него топ-пара. Третий игрок сбросил.",
    hero: ["As", "Ad"],
    villain: ["Kh", "Qd"],
    villainLine: "Противник: топ-пара, KQ",
    board: ["Ks", "8d", "2c"],
    equity: 82,
    rule: "Оверпара против топ-пары — около 80%.",
    why: "Король уже на доске, вторая пара или дама ему помогают мало. Точно 82%.",
  },
  {
    id: "kq-oesd",
    stage: "board",
    street: "Флоп",
    story: "Вы попали в топ-пару, у противника стрит с двух сторон. Третий игрок сбросил.",
    hero: ["Kh", "Qd"],
    villain: ["8s", "7c"],
    villainLine: "Противник: OESD, 87",
    board: ["6d", "5h", "Kc"],
    equity: 66,
    rule: "У него 8 аутов ≈ 34%. Вам остаётся около 66%.",
    why: "Вы впереди, но дро живое. Не 85%. Точно 66%.",
  },
  {
    id: "set-fd",
    stage: "board",
    street: "Флоп",
    story: "У вас сет, у противника флеш и стрит-дро. Третий игрок сбросил.",
    hero: ["Qs", "Qc"],
    villain: ["Ah", "Kh"],
    villainLine: "Противник: комбо-дро, AK черви",
    board: ["Qh", "Jh", "2c"],
    equity: 66,
    rule: "Сет против сильного дро — около 65%, не 90%.",
    why: "Часть червей и десяток ему помогают, часть грязные из-за фулла. Точно 66%.",
  },
  {
    id: "qj-ak",
    stage: "board",
    street: "Флоп",
    story: "Топ-пара против двух оверкарт. Третий игрок сбросил.",
    hero: ["Qh", "Jc"],
    villain: ["As", "Kd"],
    villainLine: "Противник: две оверкарты, AK",
    board: ["Qd", "8h", "3s"],
    equity: 77,
    rule: "6 аутов у них × 4 ≈ 24%. Вам около 75%.",
    why: "Туз или король вас бьёт. Остальное чаще ваше. Точно 77%.",
  },
  {
    id: "mp",
    stage: "board",
    street: "Флоп",
    story: "Средняя пара и флеш-дро нет. У противника топ-пара. Третий игрок сбросил.",
    hero: ["9h", "8h"],
    villain: ["Ah", "Qd"],
    villainLine: "Противник: топ-пара, AQ",
    board: ["Qs", "8c", "3d"],
    equity: 20,
    rule: "Средняя пара без дро — около 20%.",
    why: "Восьмёрка уже на доске. Своих аутов мало, и дама-туз впереди. Точно 20%.",
  },
  {
    id: "combo-tp",
    stage: "board",
    street: "Флоп",
    story: "Комбо-дро против топ-пары. Третий игрок сбросил.",
    hero: ["Ah", "Kh"],
    villain: ["Qs", "Jd"],
    villainLine: "Противник: топ-пара, QJ",
    board: ["Qh", "Th", "2c"],
    equity: 58,
    rule: "Флеш и стрит вместе против одной пары — около 55–60%.",
    why: "Девять червей и десятки, десятка-черва считается один раз. Вы уже слегка впереди: 58%.",
  },
  {
    id: "set-oesd",
    stage: "board",
    street: "Флоп",
    story: "Сет против стрит-дро. Третий игрок сбросил.",
    hero: ["6h", "6d"],
    villain: ["9s", "8c"],
    villainLine: "Противник: OESD, 98",
    board: ["7d", "5h", "2c"],
    equity: 70,
    rule: "Сет против восьми аутов — около 70%.",
    why: "Дро забирает около 30, не половину. Точно у сета 70%.",
  },

  {
    id: "r-aa",
    stage: "range",
    street: "Префлоп",
    story: "Баттон пушит 15bb. Вы в блайнде, третий игрок сбросил.",
    hero: ["As", "Ad"],
    villain: null,
    villainLine: "Противник: широкий пуш баттона",
    board: [],
    equity: 85,
    rule: "AA против широкого пуша — 80%+.",
    why: "Выше 47, которые просит колл. Колл без раздумий.",
  },
  {
    id: "r-kk",
    stage: "range",
    street: "Префлоп",
    story: "Баттон пушит 15bb. Вы в блайнде, третий игрок сбросил.",
    hero: ["Kh", "Kd"],
    villain: null,
    villainLine: "Противник: широкий пуш баттона",
    board: [],
    equity: 82,
    rule: "KK против широкого пуша — 80%+.",
    why: "Тузы в диапазоне есть, но их мало. Вы всё ещё сильный фаворит.",
  },
  {
    id: "r-qq",
    stage: "range",
    street: "Префлоп",
    story: "Баттон пушит 15bb. Вы в блайнде, третий игрок сбросил.",
    hero: ["Qs", "Qc"],
    villain: null,
    villainLine: "Противник: широкий пуш баттона",
    board: [],
    equity: 72,
    rule: "QQ — около 72%.",
    why: "AK и старшие пары бьют часть ренджа, остальное вы впереди. Колл.",
  },
  {
    id: "r-jj",
    stage: "range",
    street: "Префлоп",
    story: "Баттон пушит 15bb. Вы в блайнде, третий игрок сбросил.",
    hero: ["Jh", "Jd"],
    villain: null,
    villainLine: "Противник: широкий пуш баттона",
    board: [],
    equity: 64,
    rule: "JJ — около 64%.",
    why: "Уверенный колл: далеко выше 47%.",
  },
  {
    id: "r-aks",
    stage: "range",
    street: "Префлоп",
    story: "Баттон пушит 15bb. Вы в блайнде, третий игрок сбросил.",
    hero: ["As", "Ks"],
    villain: null,
    villainLine: "Противник: широкий пуш баттона",
    board: [],
    equity: 64,
    rule: "AKs — ближе к 65%.",
    why: "Одномастный туз-король против широкого пуша. Колл.",
  },
  {
    id: "r-ako",
    stage: "range",
    street: "Префлоп",
    story: "Баттон пушит 15bb. Вы в блайнде, третий игрок сбросил.",
    hero: ["Ah", "Kd"],
    villain: null,
    villainLine: "Противник: широкий пуш баттона",
    board: [],
    equity: 61,
    rule: "AKo — ближе к 60%.",
    why: "Чуть слабее одномастного, всё ещё колл.",
  },
  {
    id: "r-aq",
    stage: "range",
    street: "Префлоп",
    story: "Баттон пушит 15bb. Вы в блайнде, третий игрок сбросил.",
    hero: ["As", "Qd"],
    villain: null,
    villainLine: "Противник: широкий пуш баттона",
    board: [],
    equity: 54,
    rule: "AQ — около 55%.",
    why: "Выше 47%. Колл.",
  },
  {
    id: "r-aj",
    stage: "range",
    street: "Префлоп",
    story: "Баттон пушит 15bb. Вы в блайнде, третий игрок сбросил.",
    hero: ["Ah", "Jc"],
    villain: null,
    villainLine: "Противник: широкий пуш баттона",
    board: [],
    equity: 50,
    rule: "AJ — около 50%.",
    why: "Тонкий колл: как раз над ценой 47%.",
  },
  {
    id: "r-22",
    stage: "range",
    street: "Префлоп",
    story: "Баттон пушит 15bb. Вы в блайнде, третий игрок сбросил.",
    hero: ["2c", "2d"],
    villain: null,
    villainLine: "Противник: широкий пуш баттона",
    board: [],
    equity: 50,
    rule: "22 — около 50%, часто флип.",
    why: "Против оверкарт вы чуть впереди, против старших пар позади. В сумме около монетки. Колл.",
  },
  {
    id: "r-tt",
    stage: "range",
    street: "Префлоп",
    story: "Баттон пушит 15bb. Вы в блайнде, третий игрок сбросил.",
    hero: ["Ts", "Tc"],
    villain: null,
    villainLine: "Противник: широкий пуш баттона",
    board: [],
    equity: 57,
    rule: "TT — около 55–60%.",
    why: "Колл. Часть ренджа — оверкарты, это флипы, не проигрыш.",
  },
  {
    id: "r-kqs",
    stage: "range",
    street: "Префлоп",
    story: "Баттон пушит 15bb. Вы в блайнде, третий игрок сбросил.",
    hero: ["Kh", "Qh"],
    villain: null,
    villainLine: "Противник: широкий пуш баттона",
    board: [],
    equity: 48,
    rule: "KQs — около 48%, самая граница.",
    why: "Цена колла около 47%. Одномастный король-дама на грани колла.",
  },
  {
    id: "r-kqo",
    stage: "range",
    street: "Префлоп",
    story: "Баттон пушит 15bb. Вы в блайнде, третий игрок сбросил.",
    hero: ["Kh", "Qd"],
    villain: null,
    villainLine: "Противник: широкий пуш баттона",
    board: [],
    equity: 45,
    rule: "KQo — около 45%.",
    why: "Ниже 47%. Чаще фолд, даже если рука выглядит сильной.",
  },
  {
    id: "r-ato",
    stage: "range",
    street: "Префлоп",
    story: "Баттон пушит 15bb. Вы в блайнде, третий игрок сбросил.",
    hero: ["Ad", "Tc"],
    villain: null,
    villainLine: "Противник: широкий пуш баттона",
    board: [],
    equity: 42,
    rule: "ATo — около 42%.",
    why: "Мало для колла 15bb. Фолд.",
  },
  {
    id: "r-76s",
    stage: "range",
    street: "Префлоп",
    story: "Баттон пушит 15bb. Вы в блайнде, третий игрок сбросил.",
    hero: ["7h", "6h"],
    villain: null,
    villainLine: "Противник: широкий пуш баттона",
    board: [],
    equity: 36,
    rule: "76s — около 36%.",
    why: "Дро красивое, цены нет. Фолд.",
  },
  {
    id: "r-a5o",
    stage: "range",
    street: "Префлоп",
    story: "Баттон пушит 15bb. Вы в блайнде, третий игрок сбросил.",
    hero: ["As", "5d"],
    villain: null,
    villainLine: "Противник: широкий пуш баттона",
    board: [],
    equity: 39,
    rule: "Слабый разномастный туз — до 40%.",
    why: "Слабее ATo. Фолд.",
  },
];

export function bucketsFor(stage: EquityStage): Bucket[] {
  return stage === "range" ? RANGE_BUCKETS : BROAD;
}

export function bucketOf(stage: EquityStage, equity: number): Bucket {
  const list = bucketsFor(stage);
  return list.find((b) => equity >= b.lo && equity < b.hi) ?? list[list.length - 1]!;
}

export function judge(stage: EquityStage, equity: number, picked: string): "correct" | "close" | "wrong" {
  const list = bucketsFor(stage);
  const right = list.findIndex((b) => b.id === bucketOf(stage, equity).id);
  const guess = list.findIndex((b) => b.id === picked);
  if (guess < 0) return "wrong";
  if (guess === right) return "correct";
  if (Math.abs(guess - right) === 1) return "close";
  return "wrong";
}

export function spotsFor(stage: EquityStage): EquitySpot[] {
  return EQUITY_SPOTS.filter((s) => s.stage === stage);
}

export function shuffleSpots(stage: EquityStage): EquitySpot[] {
  const list = spotsFor(stage).slice();
  for (let i = list.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    const tmp = list[i]!;
    list[i] = list[j]!;
    list[j] = tmp;
  }
  return list;
}
